### ISSUE TITLE
use stream-oriented XML parser instead of pugixml

### ISSUE THREAD

**Issue by igagis** [igagis/svgdom#16]
like libexpat.

It should increase performance.

**Comment by JaimeIvanCervantes** [comment]
svgpp supports multiple xml parsers: http://svgpp.org/advanced.html#adding-new-xml-parser 

And by default, it uses a modified version of rapidxml that supports namespaces: https://github.com/svgpp/rapidxml_ns

I've heard good things about rapidxml performance.

**Comment by igagis** [comment]
@JaimeIvanCervantes as I understand, rapidxml is not stream-oriented, as for example libexpat is. I think it will still be slower than stream-oriented one, as there is no actual need to create XML DOM while loading SVG.

**Comment by JaimeIvanCervantes** [comment]
Yep, then you will have to use expat or xerces, but both are a bit complex though.

**Comment by igagis** [comment]
using mikroxml
