### ISSUE TITLE
Library is unusable in debug mode

### ISSUE THREAD

**Issue by saeitsystems** [igagis/svgdom#18]
After Update to latest version of svgren I permanently get an assertion in svgdom while loading simple images:
[menue-new.zip](https://github.com/igagis/svgdom/files/1230790/menue-new.zip)

Assertion:
![assertion after update](https://user-images.githubusercontent.com/25054917/29405713-fcc27728-833e-11e7-8a5a-651a653dcdff.png)

Release version runs fine and alle the images still look good ..... so I don't see a reason for an assertion.

**Comment by igagis** [comment]
Well, yes, this is due to https://github.com/igagis/svgdom/issues/13 I'm working on that.
I will remove the assertion.

**Comment by saeitsystems** [comment]
That sounds good!

**Comment by igagis** [comment]
Assertions removed. Please update to **svgdom** version 0.2.71 or later.

**Comment by saeitsystems** [comment]
I have updated to version 0.2.73 and everything is fine again! Thank you for your quick help!
