### ISSUE TITLE
CMake support 

### ISSUE THREAD

**Issue by AndySomogyi** [igagis/svgdom#34]
What do you think about adding cmake support? 

We're really interested in incorporating a svg dom type library into our library, but we use cmake, and support Mac, Linux and Windows. So, best way is if svgdom were all packaged into a single git repo, and we could just add it as a git submodule. 

I'd be willing to write the CMake build system.

**Comment by igagis** [comment]
Hi, thanks for the interest in my lib.

I know that CMake is quite popular nowadays, but I'm still considering whether it is worth to support and maintan CMake build scripts. I personally have small CMAke experience.

Note, that all my libraries are packaged to several packet systems and are cross-platform.
Installing, managing and updating libraries using packet systems is much more convenient than using submodules or copying code to your codebase.

The supported OS list is as following:
- Linux
- Windows (7+)
- Mac OS X
- Android
- iOS

Supported packet systems list is:
- **deb** (debian / ubuntu/ raspbian)
- Msys2 **pacman** (Windows)
- **Nuget** (Windows Visual Studio)
- **homebrew** (Mac OS X)
- **cocoapods** (iOS, Xcode, Mac OS X)

Would you consider if you can use those already supported distribution options?

By the way, if you are interested in rasterizing SVGs, I have the **svgren** library for that, while **svgdom** is only about reading/writing/manipulating SVG files.

**Comment by igagis** [comment]
@AndySomogyi I have corrected the installation instructions on the wiki page https://github.com/igagis/svgdom/blob/master/wiki/MainPage.adoc

**Comment by JaimeIvanCervantes** [comment]
@AndySomogyi rolling out your own CMake file to build `svgdom` and `svgren` is fairly easy, since all the dependencies are found on @igagis repos. Here's an example `CMakeLists` that I posted a while ago: https://github.com/igagis/svgren/issues/43#issuecomment-354893026
